Image_1:
  crop_bottom: 259
  crop_left: 0
  crop_right: 0
  crop_top: 0
  icx: -63.6
  icy: 2.6000000000000005
  map_x_anypoint: ../data_config/map_x_anypoint_image_0.npy
  map_y_anypoint: ../data_config/map_y_anypoint_image_0.npy
  rotate: 0.7
  shift_x: 0
  shift_y: 0
  zoom: 4.58
Image_2:
  crop_bottom: 0
  crop_left: 0
  crop_right: 357
  crop_top: 0
  icx: -61.0
  icy: 0.0
  map_x_anypoint: ../data_config/map_x_anypoint_image_1.npy
  map_y_anypoint: ../data_config/map_y_anypoint_image_1.npy
  rotate: -2.6
  shift_x: 26
  shift_y: 620
  zoom: 3.46
Image_3:
  crop_bottom: 0
  crop_left: 383
  crop_right: 0
  crop_top: 0
  icx: -59.89999999999998
  icy: 2.9
  map_x_anypoint: ../data_config/map_x_anypoint_image_2.npy
  map_y_anypoint: ../data_config/map_y_anypoint_image_2.npy
  rotate: 3.5
  shift_x: -69
  shift_y: 596
  zoom: 3.14
Image_4:
  crop_bottom: 0
  crop_left: 0
  crop_right: 0
  crop_top: 441
  icx: -57.099999999999994
  icy: -3.0
  map_x_anypoint: ../data_config/map_x_anypoint_image_3.npy
  map_y_anypoint: ../data_config/map_y_anypoint_image_3.npy
  rotate: -5.8
  shift_x: -35
  shift_y: 753
  zoom: 3.7199999999999998
camera_placement: center
camera_used: 4
