Image_1:
  alpha: -78.1
  beta: -1.7
  crop_bottom: 49
  crop_left: 0
  crop_right: 0
  crop_top: 947
  map_x_anypoint: ../data_config/map_x_anypoint_image_0.npy
  map_y_anypoint: ../data_config/map_y_anypoint_image_0.npy
  rotate: 0.7
  shift_x: 0
  shift_y: 0
  zoom: 6.36
Image_2:
  alpha: -79.2
  beta: 1.0
  crop_bottom: 0
  crop_left: 621
  crop_right: 65
  crop_top: 0
  map_x_anypoint: ../data_config/map_x_anypoint_image_1.npy
  map_y_anypoint: ../data_config/map_y_anypoint_image_1.npy
  rotate: -4.7
  shift_x: 383
  shift_y: 855
  zoom: 4.28
Image_3:
  alpha: -81.6
  beta: 0.1
  crop_bottom: 0
  crop_left: 67
  crop_right: 693
  crop_top: 0
  map_x_anypoint: ../data_config/map_x_anypoint_image_2.npy
  map_y_anypoint: ../data_config/map_y_anypoint_image_2.npy
  rotate: 2.2
  shift_x: -442
  shift_y: 609
  zoom: 4.06
Image_4:
  alpha: -68.8
  beta: 3.6
  crop_bottom: 876
  crop_left: 0
  crop_right: 0
  crop_top: 154
  map_x_anypoint: ../data_config/map_x_anypoint_image_3.npy
  map_y_anypoint: ../data_config/map_y_anypoint_image_3.npy
  rotate: 2.1
  shift_x: 35
  shift_y: 200
  zoom: 5.12
camera_placement: center
camera_used: 4
