# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(818, 664)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(2, 2, -1, 2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_open_image = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_open_image.sizePolicy().hasHeightForWidth())
        self.pushButton_open_image.setSizePolicy(sizePolicy)
        self.pushButton_open_image.setObjectName("pushButton_open_image")
        self.horizontalLayout.addWidget(self.pushButton_open_image)
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.spinBox_alpha = QtWidgets.QSpinBox(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_alpha.sizePolicy().hasHeightForWidth())
        self.spinBox_alpha.setSizePolicy(sizePolicy)
        self.spinBox_alpha.setMinimumSize(QtCore.QSize(80, 0))
        self.spinBox_alpha.setMinimum(20)
        self.spinBox_alpha.setMaximum(120)
        self.spinBox_alpha.setProperty("value", 90)
        self.spinBox_alpha.setObjectName("spinBox_alpha")
        self.horizontalLayout.addWidget(self.spinBox_alpha)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addWidget(self.frame_2)
        self.lable_image = QtWidgets.QLabel(self.centralwidget)
        self.lable_image.setMinimumSize(QtCore.QSize(800, 600))
        self.lable_image.setFrameShape(QtWidgets.QFrame.Box)
        self.lable_image.setText("")
        self.lable_image.setAlignment(QtCore.Qt.AlignCenter)
        self.lable_image.setObjectName("lable_image")
        self.verticalLayout.addWidget(self.lable_image)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_open_image.setText(_translate("MainWindow", "Open Image"))
        self.label.setText(_translate("MainWindow", "Alpha: "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
